project:
  type: website
  output-dir: jekyll/markdown_output/posts
 
format:
  markdown:
    wrap: none
    html-math-method: plain
    df-print: kable
    output-file: index.md
    code-fold: false
    toc: false
    execute:
      echo: true
      eval: true
      warning: true
      error: true
    # Specifically disable fenced divs and other special Markdown extensions
    md-extensions:
      -fenced_divs
      -attributes
      -raw_html
      -html_blocks
      -markdown_in_html_blocks
    prefer-html: false
    variant: gfm
    fig-format: png
    fig-cap-location: top
    html-images: false
    html-tables: false
    # Use standard markdown instead of HTML
    reference-location: document
    link-citations: true